// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reservaciones_dividadesPor_Sesiones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reservaciones_dividadesPor_Sesiones));
        
        string IMigrationMetadata.Id
        {
            get { return "201708020400464_reservaciones_dividadesPor_Sesiones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
