// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eventos_addedField_totalPorServicios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eventos_addedField_totalPorServicios));
        
        string IMigrationMetadata.Id
        {
            get { return "201708312154172_eventos_addedField_totalPorServicios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
