// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changued_fields_eventos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changued_fields_eventos));
        
        string IMigrationMetadata.Id
        {
            get { return "201709020545287_changued_fields_eventos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
