// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class banquetes_addedFieldsfromParent_TotalPorServicios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banquetes_addedFieldsfromParent_TotalPorServicios));
        
        string IMigrationMetadata.Id
        {
            get { return "201709131844055_banquetes_addedFieldsfromParent_TotalPorServicios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
