// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nonRequieres_servicioID_in_RerservacionServicioTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonRequieres_servicioID_in_RerservacionServicioTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707302352248_nonRequieres_servicioID_in_RerservacionServicioTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
