// <auto-generated />
namespace Jerry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class baquetes_addedFiedls_Platillos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baquetes_addedFiedls_Platillos));
        
        string IMigrationMetadata.Id
        {
            get { return "201709040057009_baquetes_addedFiedls_Platillos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
